In [ ]:
import torch
import numpy as np

# 파이토치와 넘파이 모듈을 import하는 과정


In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
# 파이토치의 tensor를 생성하는 과정정

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# 넘파이로 생성한 배열을 파이토치의 tensor로 변환하는 과정

In [ ]:
x_ones = torch.ones_like(x_data)  # x_data와 같은 크기의 텐서를 생성
x_rand = torch.rand_like(x_data, dtype=torch.float)  # x_data와 같은 크기의 랜덤 텐서를 생성\
print(f"Ones Tensor: \n{x_ones} \n")
print(f"Random Tensor: \n{x_rand} \n")
# 네, 맞아요! x_data와 동일한 shape을 가지면서, 값은 모두 1이거나(ones_like), 0~1 사이의 랜덤값(rand_like)으로 채워진 텐서를 생성하는 코드입니다.

Ones Tensor: 
tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
tensor([[0.9660, 0.8595],
        [0.6776, 0.6279]]) 



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
print(f"Random Tensor with shape {shape}: \n{rand_tensor} \n")
# 지정한 shape을 가지는 랜덤 텐서를 생성하는 과정
ones_tensor = torch.ones(shape)
print(f"Ones Tensor with shape {shape}: \n{ones_tensor} \n")
# 지정한 shape을 가지는 값이 모두 1인 텐서를 생성하는 과정
zeros_tensor = torch.zeros(shape)
print(f"Zeros Tensor with shape {shape}: \n{zeros_tensor} \n") 
rand_ten = torch.rand(5,5,5)
print(rand_ten)

Random Tensor with shape (2, 3): 
tensor([[0.0148, 0.2284, 0.8465],
        [0.3761, 0.7221, 0.7440]]) 

Ones Tensor with shape (2, 3): 
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor with shape (2, 3): 
tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[[0.2602, 0.4719, 0.4669, 0.1427, 0.6810],
         [0.6590, 0.4341, 0.4691, 0.5906, 0.5982],
         [0.5334, 0.9127, 0.4013, 0.3471, 0.1583],
         [0.4974, 0.4157, 0.6006, 0.3386, 0.1991],
         [0.9607, 0.8800, 0.9755, 0.4046, 0.7035]],

        [[0.4164, 0.7476, 0.7618, 0.8544, 0.0223],
         [0.1989, 0.9639, 0.2227, 0.5991, 0.6823],
         [0.2175, 0.8278, 0.0040, 0.3746, 0.8585],
         [0.6427, 0.7277, 0.0332, 0.9841, 0.0525],
         [0.2891, 0.0182, 0.8227, 0.1017, 0.2432]],

        [[0.6066, 0.8384, 0.1012, 0.2293, 0.1283],
         [0.9340, 0.0678, 0.9944, 0.1375, 0.3401],
         [0.9685, 0.8032, 0.3260, 0.9006, 0.3390],
         [0.8246, 0.9884, 0.2174, 0.3131, 0.2595],
         [0.2129, 

In [7]:
tensor =  torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [8]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [9]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0  # 두 번째 열을 0으로 설정
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
# tensor를 세로로 이어붙이는 과정
t2 = torch.cat([tensor, tensor, tensor], dim=0)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
print(f"tensor.mul(tensor): \n{tensor.mul(tensor)} \n")
print(f"tensor * tensor: \n{tensor * tensor} \n")
print(f"tensor.matmul(tensor.T): \n{tensor.matmul(tensor.T)} \n")
print(f"tensor @ tensor.T: \n{tensor @ tensor.T} \n")
print(f"tensor.sum(): \n{tensor.sum()} \n")
# mul은 두 텐서의 원소별(element-wise) 곱셈을 의미합니다.
# 즉, tensor.mul(tensor)는 같은 위치의 값끼리 곱해서 새로운 텐서를 만듭니다.
# tensor * tensor 역시 원소별 곱셈을 의미하며, mul과 동일한 결과를 냅니다.
# tensor.matmul(tensor.T)는 텐서와 그 전치행렬(T) 간의 행렬 곱을 수행합니다.
# tensor @ tensor.T 역시 행렬 곱 연산자로, matmul과 같은 결과를 반환합니다.
# tensor.sum()은 텐서의 모든 원소의 합을 계산합니다.

tensor.mul(tensor): 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor: 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor.matmul(tensor.T): 
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T: 
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor.sum(): 
12.0 



In [19]:
tensor.add_(5)
print(tensor)
# 인플레이스 연산은 메모리를 절약할 수 있지만, 미분을 계산할 때 
# 연산 이력이 즉시 사라지기 때문에 문제가 될 수 있습니다. 
# 따라서 인플레이스 연산의 사용은 권장되지 않습니다.

tensor([[21., 20., 21., 21.],
        [21., 20., 21., 21.],
        [21., 20., 21., 21.],
        [21., 20., 21., 21.]])


In [20]:
n = tensor.numpy()
print(f"tensor to numpy: \n{n} \n")

tensor to numpy: 
[[21. 20. 21. 21.]
 [21. 20. 21. 21.]
 [21. 20. 21. 21.]
 [21. 20. 21. 21.]] 



In [ ]:
`out` 파라미터는 결과를 저장할 배열을 지정하는 역할을 합니다.  
즉, `np.add(n, 1, out=n)`은 `n + 1`의 결과를 새로운 배열에 저장하지 않고, 기존의 `n` 배열에 바로 덮어씁니다(메모리 절약, 인플레이스 연산).  
따라서 `n`의 값이 직접 변경됩니다.